# Generated by Django 3.0.8 on 2020-07-16 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0007_guides_quotedcharges'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('messagesID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sendAt', models.DateTimeField(auto_now=True)),
                ('recipientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageRecipient', related_query_name='messageRecipient', to='profiles.User')),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageSender', related_query_name='messageSender', to='profiles.User')),
            ],
        ),
    ]
