# Generated by Django 3.0.8 on 2020-07-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200717_2200'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageRecipient', related_query_name='messageRecipient', to='profiles.userProfile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='senderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageSender', related_query_name='messageSender', to='profiles.userProfile'),
        ),
    ]
