# Generated by Django 3.0.8 on 2020-07-25 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0003_auto_20200725_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='itineraryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary', models.FileField(blank=True, null=True, upload_to='sampleItinerary')),
                ('messagesID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='messageToTraveler',
            fields=[
                ('messagesID', models.AutoField(primary_key=True, serialize=False)),
                ('tripID', models.IntegerField()),
                ('recipientID', models.IntegerField()),
                ('content', models.TextField()),
                ('sendAt', models.DateTimeField(auto_now=True)),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
