# Generated by Django 3.0.8 on 2020-07-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryCode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('stateCode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stateName', models.CharField(max_length=100)),
                ('countryCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
            ],
        ),
    ]
