# Generated by Django 3.0.8 on 2020-07-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('passportNo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Undefined')], default='U', max_length=1)),
                ('profilePic', models.ImageField(upload_to='profilePicture')),
            ],
        ),

         migrations.CreateModel(
            name='Guides',
           fields=[
                ('guidesID', models.AutoField(primary_key=True, serialize=False)),
                ('licenses', models.FileField(blank=True, null=True, upload_to='license')),
                ('itinerary', models.FileField(upload_to='sampleItinerary')),
                ('introduction', models.TextField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
                ('guidingCountry', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='country.Country')),
                ('guidingState', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='country.State')),
            ],
        ),
    
    ]
