# Generated by Django 3.0.8 on 2020-07-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('passportNo', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Undefined')], default='U', max_length=1)),
                ('profilePic', models.ImageField(upload_to='profilePicture')),
            ],
        ),
    ]
