# Generated by Django 3.0.8 on 2020-07-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avgRating',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('guidesID', models.AutoField(primary_key=True, serialize=False)),
                ('licenses', models.FileField(blank=True, null=True, upload_to='license')),
                ('itinerary', models.FileField(upload_to='sampleItinerary')),
                ('introduction', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
    ]
