# Generated by Django 3.0.8 on 2020-07-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200713_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avgRating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
