# Generated by Django 3.0.8 on 2020-07-14 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travelers',
            fields=[
                ('travelersID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
    ]
