# Generated by Django 3.0.8 on 2020-07-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200715_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='guides',
            name='applicationStatus',
            field=models.CharField(choices=[('APPROVED', 'Approved by Admins'), ('REJECTED', 'Rejected by Admins'), ('PENDING', 'Pending for Approval')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='guides',
            name='position',
            field=models.CharField(choices=[('GUIDES', 'Guides'), ('PLANNERS', 'Planners')], default='PLANNERS', max_length=30),
        ),
    ]
