# Generated by Django 3.0.8 on 2020-07-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='guides',
            name='quotedCharges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
