# Generated by Django 3.0.8 on 2020-07-17 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_guides_quotedcharges'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Undefined')], default='U', max_length=1)),
                ('passportNo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('dateOfBirth', models.DateField()),
                ('profilePic', models.ImageField(upload_to='profilePicture')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='guides',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userProfile'),
        ),
        migrations.AlterField(
            model_name='travelers',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userProfile'),
        ),
    ]
