# Generated by Django 3.0.8 on 2020-07-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20200716_2218'),
        ('country', '0001_initial'),
        ('profiles', '0009_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guides',
            new_name='Guide',
        ),
    ]
