# Generated by Django 3.0.8 on 2020-07-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20200717_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity',
            field=models.CharField(choices=[('GUIDES', 'Guides'), ('TRAVELERS', 'Travelers')], default='Travelers', max_length=30),
        ),
    ]
