# Generated by Django 3.0.8 on 2020-07-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20200716_2218'),
        ('country', '0001_initial'),
        ('profiles', '0011_userprofile_identity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guide',
            new_name='guideProfile',
        ),
    ]
