# Generated by Django 3.0.8 on 2020-07-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200719_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profilePic',
        ),
    ]
