# Generated by Django 3.0.8 on 2020-07-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_userprofile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='guide',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
