# Generated by Django 3.0.8 on 2020-07-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_userprofile_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='guide',
        ),
    ]
