# Generated by Django 3.0.8 on 2020-07-21 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0016_auto_20200722_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofile',
            name='userID',
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
