# Generated by Django 3.0.8 on 2020-07-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20200722_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='userProfiles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.userProfile'),
            preserve_default=False,
        ),
    ]
