# Generated by Django 3.0.8 on 2020-07-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_guideprofile_userprofiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofile',
            name='userProfiles',
        ),
    ]
