# Generated by Django 3.0.8 on 2020-07-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('profiles', '0004_auto_20200715_0302'),
        ('trips', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelerreviews',
            name='tripID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='trips.Trip'),
        ),
        migrations.AddField(
            model_name='guidereviews',
            name='senderID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.Guides'),
        ),
        migrations.AddField(
            model_name='guidereviews',
            name='travelerID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.Travelers'),
        ),
        migrations.AddField(
            model_name='guidereviews',
            name='tripID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='trips.Trip'),
        ),
    ]
