# Generated by Django 3.0.8 on 2020-07-16 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_guides_quotedcharges'),
        ('trips', '0002_auto_20200716_2218'),
        ('reviews', '0002_auto_20200715_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('reviewContent', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1)),
                ('GuideID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.Guides')),
                ('recipientID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reviewRecipient', related_query_name='reviewRecipient', to='profiles.User')),
                ('senderID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reviewSender', related_query_name='reviewSender', to='profiles.User')),
                ('tripID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='trips.Trip')),
            ],
        ),
        migrations.RemoveField(
            model_name='travelerreviews',
            name='GuideID',
        ),
        migrations.RemoveField(
            model_name='travelerreviews',
            name='senderID',
        ),
        migrations.RemoveField(
            model_name='travelerreviews',
            name='tripID',
        ),
        migrations.DeleteModel(
            name='guideReviews',
        ),
        migrations.DeleteModel(
            name='travelerReviews',
        ),
    ]
