# Generated by Django 3.0.8 on 2020-07-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200717_2200'),
        ('reviews', '0003_auto_20200716_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='recipientID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reviewRecipient', related_query_name='reviewRecipient', to='profiles.userProfile'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='senderID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reviewSender', related_query_name='reviewSender', to='profiles.userProfile'),
        ),
    ]
