# Generated by Django 3.0.8 on 2020-07-25 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0005_remove_reviews_guideid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsForGuides',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('recipientID', models.IntegerField()),
                ('tripID', models.IntegerField()),
                ('reviewContent', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1)),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsForTravelers',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('recipientID', models.IntegerField()),
                ('tripID', models.IntegerField()),
                ('reviewContent', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1)),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
