# Generated by Django 3.0.8 on 2020-07-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
        ('profiles', '0004_auto_20200715_0302'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('tripID', models.AutoField(primary_key=True, serialize=False)),
                ('tripStartDate', models.DateField()),
                ('tripEndDate', models.DateField()),
                ('numOfPeople', models.IntegerField()),
                ('quotedCharges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for Acception'), ('ACCEPTED', 'Accepted by Guides'), ('REJECTED', 'Rejected by Guides'), ('QUOTED', 'Charges Quoted by Guides'), ('IN PROGRESS', 'Planning/Guiding In Progress'), ('COMPLETED', 'Planning/Guiding Completed'), ('CANCELLED', 'The Request for Service is Cancelled by Travelers')], default='WAITING', max_length=32)),
                ('countryID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='country.Country')),
                ('guidesID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.Guides')),
                ('stateID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='country.State')),
                ('travelerID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.Travelers')),
            ],
        ),
    ]
