# Generated by Django 3.0.8 on 2020-07-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='quotedCharges',
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending for Acception'), ('ACCEPTED', 'Accepted by Guides'), ('REJECTEsD', 'Rejected by Guides'), ('IN PROGRESS', 'Planning/Guiding In Progress'), ('COMPLETED', 'Planning/Guiding Completed')], default='PENDING', max_length=32),
        ),
    ]
