# Generated by Django 3.0.8 on 2020-07-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_remove_guideprofile_userprofiles'),
        ('trips', '0002_auto_20200716_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travelerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Travelers'),
        ),
    ]
