# Generated by Django 3.0.8 on 2020-07-24 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20200723_2325'),
        ('trips', '0006_auto_20200724_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripguide',
            name='guides',
            field=models.OneToOneField(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.guideProfile'),
        ),
        migrations.AlterField(
            model_name='tripguide',
            name='tripID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip'),
        ),
    ]
